export const exampleActivities = [
  {
    name: "A",
    precedents: [],
    optimist: 2,
    probable: 2,
    pessimist: 2,
    cost: 2000000,
    acceleration: 2.5,
    acceleration_cost: 13500000,
  },
  {
    name: "B",
    precedents: ["A"],
    optimist: 1,
    probable: 2,
    pessimist: 3,
    cost: 13870420,
    acceleration: 3,
    acceleration_cost: 14950000,
  },
  {
    name: "C",
    precedents: ["B"],
    optimist: 3,
    probable: 3,
    pessimist: 3,
    cost: 9870000,
    acceleration: null,
    acceleration_cost: null,
  },
  {
    name: "D",
    precedents: ["A"],
    optimist: 5,
    probable: 5,
    pessimist: 5,
    cost: 16230450,
    acceleration: 5,
    acceleration_cost: 17890000,
  },
  {
    name: "E",
    precedents: ["B", "C"],
    optimist: 1,
    probable: 2,
    pessimist: 3,
    cost: 14230890,
    acceleration: 4,
    acceleration_cost: 15338000,
  },
  {
    name: "F",
    precedents: ["D"],
    optimist: 6,
    probable: 6,
    pessimist: 6,
    cost: 7845360,
    acceleration: null,
    acceleration_cost: null,
  },
  {
    name: "G",
    precedents: ["D"],
    optimist: 3,
    probable: 3,
    pessimist: 3,
    cost: 3245000,
    acceleration: null,
    acceleration_cost: null,
  },
  {
    name: "H",
    precedents: ["F", "G"],
    optimist: 1,
    probable: 2,
    pessimist: 3,
    cost: 13245670,
    acceleration: null,
    acceleration_cost: null,
  },
  {
    name: "I",
    precedents: ["E"],
    optimist: 2,
    probable: 4,
    pessimist: 6,
    cost: 15220000,
    acceleration: 5,
    acceleration_cost: 16450000,
  },
  {
    name: "J",
    precedents: ["I"],
    optimist: 1.5,
    probable: 1.5,
    pessimist: 1.5,
    cost: 19320000,
    acceleration: 8,
    acceleration_cost: 20890000,
  },
  {
    name: "K",
    precedents: ["J", "H"],
    optimist: 2,
    probable: 2,
    pessimist: 2,
    cost: 14870000,
    acceleration: 6,
    acceleration_cost: 15450000,
  },
];
